basePath: /api
definitions:
  dto.CreateClientDTO:
    properties:
      address:
        type: string
      email:
        type: string
      name:
        minLength: 2
        type: string
      phone:
        type: string
    required:
    - email
    - name
    type: object
  dto.UpdateClientDTO:
    properties:
      address:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  model.Client:
    properties:
      address:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        description: необязательный телефон
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Kamelia API
  version: "1.0"
paths:
  /clients:
    get:
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Page
        in: query
        name: page
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Client'
            type: array
      summary: List clients
      tags:
      - clients
    post:
      parameters:
      - description: Client data
        in: body
        name: client
        required: true
        schema:
          $ref: '#/definitions/dto.CreateClientDTO'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Client'
      summary: Create client
      tags:
      - clients
  /clients/{id}:
    delete:
      parameters:
      - description: Client ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: Delete client
      tags:
      - clients
    patch:
      parameters:
      - description: Client ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update data
        in: body
        name: client
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateClientDTO'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Client'
      summary: Update client
      tags:
      - clients
swagger: "2.0"
